#!/usr/bin/env node
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';
import { existsSync, readFileSync, writeFileSync, mkdirSync, readdirSync } from 'fs';
import { createInterface } from 'readline/promises';
import { stdin as input, stdout as output } from 'process';
import { stringify as stringifyYaml } from 'yaml';

const __dirname = dirname(fileURLToPath(import.meta.url));

export function sanitizeId(name: string): string {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9-]/g, '-')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '');
}

function getVersion(): string {
  const pkg = JSON.parse(readFileSync(join(__dirname, '..', 'package.json'), 'utf-8'));
  return pkg.version as string;
}

function maskSecret(value: string): string {
  if (value.length <= 8) return '****';
  return value.slice(0, 4) + '****';
}

const LLM_PROVIDERS = ['anthropic', 'openai', 'gemini'] as const;
const LLM_LABELS: Record<string, string> = {
  anthropic: 'Anthropic',
  openai: 'OpenAI',
  gemini: 'Gemini',
};
const LLM_KEY_NAMES: Record<string, string> = {
  anthropic: 'ANTHROPIC_API_KEY',
  openai: 'OPENAI_API_KEY',
  gemini: 'GEMINI_API_KEY',
};
const LLM_KEY_PROMPTS: Record<string, string> = {
  anthropic: 'Anthropic API key (console.anthropic.com/api-keys)',
  openai: 'OpenAI API key (platform.openai.com/api-keys)',
  gemini: 'Gemini API key (aistudio.google.com/apikey)',
};

const EMAIL_PROVIDERS = ['resend', 'gmail'] as const;
const EMAIL_PROVIDER_LABELS: Record<string, string> = {
  resend: 'Resend',
  gmail: 'Gmail',
};

const SUBSCRIBER_STORES = ['json', 'supabase', 'google-sheets'] as const;
const STORE_LABELS: Record<string, string> = {
  json: 'JSON file',
  supabase: 'Supabase',
  'google-sheets': 'Google Sheets',
};

export interface InitAnswers {
  productName: string;
  repo: string;
  voice: string;
  llmProvider: string;
  llmApiKey: string;
  subscriberStore: string;
  emailProvider: string;
  githubToken: string;
  resendApiKey?: string;
  fromEmail: string;
  supabaseUrl?: string;
  supabaseServiceKey?: string;
  googleSheetsSpreadsheetId?: string;
  googleServiceAccountEmail?: string;
  googlePrivateKey?: string;
}

export function buildEnvContent(answers: InitAnswers): string {
  const lines: string[] = [
    '# Cryyer Environment Variables',
    '# Generated by cryyer init',
    '',
    '# GitHub personal access token (repo scope required)',
    `GITHUB_TOKEN=${answers.githubToken}`,
    '',
    `# Email provider: ${EMAIL_PROVIDERS.join(', ')}`,
    `EMAIL_PROVIDER=${answers.emailProvider}`,
  ];

  if (answers.emailProvider === 'resend') {
    lines.push('', '# Resend API key for email delivery');
    lines.push(`RESEND_API_KEY=${answers.resendApiKey ?? ''}`);
  }

  lines.push(
    '',
    '# Default sender email address',
    `FROM_EMAIL=${answers.fromEmail}`,
    '',
    `# LLM provider: ${LLM_PROVIDERS.join(', ')}`,
    `LLM_PROVIDER=${answers.llmProvider}`,
    '',
    `# ${LLM_LABELS[answers.llmProvider]} API key`,
    `${LLM_KEY_NAMES[answers.llmProvider]}=${answers.llmApiKey}`,
    '',
    `# Subscriber store: ${SUBSCRIBER_STORES.join(', ')}`,
    `SUBSCRIBER_STORE=${answers.subscriberStore}`,
  );

  if (answers.subscriberStore === 'supabase') {
    lines.push('', '# Supabase configuration');
    lines.push(`SUPABASE_URL=${answers.supabaseUrl ?? ''}`);
    lines.push(`SUPABASE_SERVICE_KEY=${answers.supabaseServiceKey ?? ''}`);
  }

  if (answers.subscriberStore === 'google-sheets') {
    lines.push('', '# Google Sheets configuration');
    lines.push(`GOOGLE_SHEETS_SPREADSHEET_ID=${answers.googleSheetsSpreadsheetId ?? ''}`);
    lines.push(`GOOGLE_SERVICE_ACCOUNT_EMAIL=${answers.googleServiceAccountEmail ?? ''}`);
    lines.push(`GOOGLE_PRIVATE_KEY=${answers.googlePrivateKey ?? ''}`);
  }

  lines.push('');
  return lines.join('\n');
}

export function buildSubscribersJson(productId: string): string {
  const data = [
    { email: 'alice@example.com', name: 'Alice', productIds: [productId] },
  ];
  return JSON.stringify(data, null, 2) + '\n';
}

const GITIGNORE_ENTRIES = ['.env', 'subscribers.json', 'email-log.json'];
const GITIGNORE_HEADER = '# cryyer';

export function buildGitignoreContent(existing: string | null): string {
  if (!existing) {
    return GITIGNORE_HEADER + '\n' + GITIGNORE_ENTRIES.join('\n') + '\n';
  }

  const existingLines = existing.split('\n');
  const missing = GITIGNORE_ENTRIES.filter(
    (entry) => !existingLines.some((line) => line.trim() === entry)
  );

  if (missing.length === 0) return existing;

  const suffix = existing.endsWith('\n') ? '' : '\n';
  return existing + suffix + '\n' + GITIGNORE_HEADER + '\n' + missing.join('\n') + '\n';
}

function parseSelection(raw: string, options: readonly string[], defaultIndex: number): string {
  const trimmed = raw.trim();
  if (!trimmed) return options[defaultIndex];
  const num = parseInt(trimmed, 10);
  if (num >= 1 && num <= options.length) return options[num - 1];
  throw new Error(`Invalid selection: "${trimmed}". Enter a number 1-${options.length}.`);
}

export async function main(): Promise<void> {
  const rl = createInterface({ input, output });
  const cwd = process.cwd();

  let version: string;
  try {
    version = getVersion();
  } catch {
    version = 'dev';
  }

  console.log('');
  console.log(`  cryyer v${version}`);
  console.log('');
  console.log(`  Setting up cryyer in ${cwd}`);
  console.log('');

  try {
    // Check if products already exist
    const productsDir = join(cwd, 'products');
    let hasExistingProducts = false;
    if (existsSync(productsDir)) {
      const existing = readdirSync(productsDir).filter((f) => f.endsWith('.yaml') || f.endsWith('.yml'));
      if (existing.length > 0) {
        hasExistingProducts = true;
        console.log(`  Found existing products: ${existing.map((f) => f.replace(/\.ya?ml$/, '')).join(', ')}`);
        const rawAdd = await rl.question('  Add another product? (Y/n): ');
        if (rawAdd.trim().toLowerCase() === 'n') {
          console.log('  Skipping product setup.');
          console.log('');
          rl.close();
          return;
        }
        console.log('');
      }
    }

    // --- Phase 1: Product ---
    const rawName = await rl.question('? Product name: ');
    const productName = rawName.trim();
    if (!productName) throw new Error('Product name is required');

    const rawRepo = await rl.question('? GitHub repo (owner/repo): ');
    const repo = rawRepo.trim();
    if (!repo || !repo.includes('/')) throw new Error('GitHub repo must be in owner/repo format');

    const rawVoice = await rl.question('? Voice/tone: ');
    const voice = rawVoice.trim();
    if (!voice) throw new Error('Voice/tone is required');

    const productId = sanitizeId(productName);
    const emailSubjectTemplate = `{{weekOf}} Weekly Update — ${productName}`;

    console.log('');

    // --- Phase 2: LLM provider ---
    const llmPrompt = `? LLM provider (${LLM_PROVIDERS.map((p, i) => `${i + 1}=${LLM_LABELS[p]}`).join(', ')}) [1]: `;
    const rawLlm = await rl.question(llmPrompt);
    const llmProvider = parseSelection(rawLlm, LLM_PROVIDERS, 0);

    const rawLlmKey = await rl.question(`? ${LLM_KEY_PROMPTS[llmProvider]}: `);
    const llmApiKey = rawLlmKey.trim();
    if (!llmApiKey) throw new Error(`${LLM_LABELS[llmProvider]} API key is required`);

    console.log('');

    // --- Phase 3: Subscriber store ---
    const storePrompt = `? Subscriber store (${SUBSCRIBER_STORES.map((s, i) => `${i + 1}=${STORE_LABELS[s]}`).join(', ')}) [1]: `;
    const rawStore = await rl.question(storePrompt);
    const subscriberStore = parseSelection(rawStore, SUBSCRIBER_STORES, 0);

    // Collect store-specific credentials
    let supabaseUrl: string | undefined;
    let supabaseServiceKey: string | undefined;
    let googleSheetsSpreadsheetId: string | undefined;
    let googleServiceAccountEmail: string | undefined;
    let googlePrivateKey: string | undefined;

    if (subscriberStore === 'supabase') {
      const rawUrl = await rl.question('? Supabase URL: ');
      supabaseUrl = rawUrl.trim();
      if (!supabaseUrl) throw new Error('Supabase URL is required');

      const rawKey = await rl.question('? Supabase service key: ');
      supabaseServiceKey = rawKey.trim();
      if (!supabaseServiceKey) throw new Error('Supabase service key is required');
    }

    if (subscriberStore === 'google-sheets') {
      const rawId = await rl.question('? Google Sheets spreadsheet ID: ');
      googleSheetsSpreadsheetId = rawId.trim();
      if (!googleSheetsSpreadsheetId) throw new Error('Spreadsheet ID is required');

      const rawEmail = await rl.question('? Google service account email: ');
      googleServiceAccountEmail = rawEmail.trim();
      if (!googleServiceAccountEmail) throw new Error('Service account email is required');

      const rawPk = await rl.question('? Google private key: ');
      googlePrivateKey = rawPk.trim();
      if (!googlePrivateKey) throw new Error('Private key is required');
    }

    console.log('');

    // --- Phase 4: Email provider ---
    const emailPrompt = `? Email provider (${EMAIL_PROVIDERS.map((p, i) => `${i + 1}=${EMAIL_PROVIDER_LABELS[p]}`).join(', ')}) [1]: `;
    const rawEmail = await rl.question(emailPrompt);
    const emailProvider = parseSelection(rawEmail, EMAIL_PROVIDERS, 0);

    console.log('');

    // --- Phase 5: Common credentials ---
    const rawGithubToken = await rl.question('? GitHub token (github.com/settings/tokens, "repo" scope): ');
    const githubToken = rawGithubToken.trim();
    if (!githubToken) throw new Error('GitHub token is required');

    let resendApiKey: string | undefined;
    if (emailProvider === 'resend') {
      const rawResendKey = await rl.question('? Resend API key (resend.com/api-keys): ');
      resendApiKey = rawResendKey.trim();
      if (!resendApiKey) throw new Error('Resend API key is required');
    }

    const rawFromEmail = await rl.question('? Sender email address: ');
    const fromEmail = rawFromEmail.trim();
    if (!fromEmail) throw new Error('Sender email address is required');

    console.log('');

    // --- Generate files ---
    const created: Array<[string, string]> = [];

    // 1. Product YAML
    if (!existsSync(productsDir)) {
      mkdirSync(productsDir, { recursive: true });
    }

    const yamlPath = join(productsDir, `${productId}.yaml`);
    let writeYaml = true;

    if (existsSync(yamlPath)) {
      const rawOverwrite = await rl.question(`  ${productId}.yaml already exists. Overwrite? (y/N): `);
      writeYaml = rawOverwrite.trim().toLowerCase() === 'y';
    }

    if (writeYaml) {
      const productConfig = { id: productId, name: productName, repo, emailSubjectTemplate, voice };
      const yaml = `# Product configuration for ${productName}\n` + stringifyYaml(productConfig);
      writeFileSync(yamlPath, yaml, 'utf-8');
      created.push([`products/${productId}.yaml`, 'Product configuration']);
    }

    // 2. .env
    const envPath = join(cwd, '.env');
    let writeEnv = true;

    if (existsSync(envPath)) {
      const rawOverwrite = await rl.question('  .env already exists. Overwrite? (y/N): ');
      writeEnv = rawOverwrite.trim().toLowerCase() === 'y';
    }

    if (writeEnv) {
      const answers: InitAnswers = {
        productName, repo, voice, llmProvider, llmApiKey,
        subscriberStore, emailProvider, githubToken, resendApiKey, fromEmail,
        supabaseUrl, supabaseServiceKey,
        googleSheetsSpreadsheetId, googleServiceAccountEmail, googlePrivateKey,
      };
      const envContent = buildEnvContent(answers);
      writeFileSync(envPath, envContent, 'utf-8');
      created.push(['.env', 'API keys and settings']);
    }

    // 3. subscribers.json (only for JSON store)
    if (subscriberStore === 'json') {
      const subscribersPath = join(cwd, 'subscribers.json');
      if (!existsSync(subscribersPath)) {
        writeFileSync(subscribersPath, buildSubscribersJson(productId), 'utf-8');
        created.push(['subscribers.json', 'Subscriber list (edit to add emails)']);
      }
    }

    // 4. .gitignore
    const gitignorePath = join(cwd, '.gitignore');
    const existingGitignore = existsSync(gitignorePath)
      ? readFileSync(gitignorePath, 'utf-8')
      : null;
    const newGitignore = buildGitignoreContent(existingGitignore);

    if (newGitignore !== existingGitignore) {
      writeFileSync(gitignorePath, newGitignore, 'utf-8');
      created.push(['.gitignore', existingGitignore ? 'Updated with cryyer entries' : 'Ignores .env and data files']);
    }

    // --- Summary ---
    if (created.length > 0) {
      console.log('  Created:');
      const maxPath = Math.max(...created.map(([p]) => p.length));
      for (const [filePath, desc] of created) {
        console.log(`    ${filePath.padEnd(maxPath + 4)}${desc}`);
      }
    }

    console.log('');
    console.log('  Next steps:');
    let step = 1;
    if (emailProvider === 'gmail') {
      console.log(`    ${step}. Authorize Gmail     npx cryyer auth gmail`);
      step++;
    }
    if (subscriberStore === 'json') {
      console.log(`    ${step}. Add subscribers     Edit subscribers.json`);
    } else if (subscriberStore === 'supabase') {
      console.log(`    ${step}. Add subscribers     Set up your Supabase beta_testers table`);
    } else {
      console.log(`    ${step}. Add subscribers     Add rows to your Google Sheet`);
    }
    step++;
    console.log(`    ${step}. Validate setup      npx cryyer check`);
    step++;
    console.log(`    ${step}. Preview a draft     npx cryyer run --dry-run`);
    console.log('');
    console.log('  Docs: https://cryyer.dev');
    console.log('');
  } finally {
    rl.close();
  }
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  main().catch((err) => {
    console.error('Fatal error:', err);
    process.exit(1);
  });
}
