#!/usr/bin/env node
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';
import { existsSync, readFileSync, writeFileSync, mkdirSync, readdirSync } from 'fs';
import { createInterface } from 'readline/promises';
import { stdin as input, stdout as output } from 'process';
import { stringify as stringifyYaml } from 'yaml';

const __dirname = dirname(fileURLToPath(import.meta.url));

export function sanitizeId(name: string): string {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9-]/g, '-')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '');
}

function getVersion(): string {
  const pkg = JSON.parse(readFileSync(join(__dirname, '..', 'package.json'), 'utf-8'));
  return pkg.version as string;
}

function maskSecret(value: string): string {
  if (value.length <= 8) return '****';
  return value.slice(0, 4) + '****';
}

const LLM_PROVIDERS = ['anthropic', 'openai', 'gemini'] as const;
const LLM_LABELS: Record<string, string> = {
  anthropic: 'Anthropic',
  openai: 'OpenAI',
  gemini: 'Gemini',
};
const LLM_KEY_NAMES: Record<string, string> = {
  anthropic: 'ANTHROPIC_API_KEY',
  openai: 'OPENAI_API_KEY',
  gemini: 'GEMINI_API_KEY',
};
const LLM_KEY_PROMPTS: Record<string, string> = {
  anthropic: 'Anthropic API key (console.anthropic.com/api-keys)',
  openai: 'OpenAI API key (platform.openai.com/api-keys)',
  gemini: 'Gemini API key (aistudio.google.com/apikey)',
};

const EMAIL_PROVIDERS = ['resend', 'gmail'] as const;
const EMAIL_PROVIDER_LABELS: Record<string, string> = {
  resend: 'Resend',
  gmail: 'Gmail',
};

const SUBSCRIBER_STORES = ['json', 'supabase', 'google-sheets'] as const;
const STORE_LABELS: Record<string, string> = {
  json: 'JSON file',
  supabase: 'Supabase',
  'google-sheets': 'Google Sheets',
};

export interface InitAnswers {
  productName: string;
  repo: string;
  voice: string;
  llmProvider: string;
  llmApiKey: string;
  subscriberStore: string;
  emailProvider: string;
  githubToken: string;
  resendApiKey?: string;
  fromEmail: string;
  supabaseUrl?: string;
  supabaseServiceKey?: string;
  googleSheetsSpreadsheetId?: string;
  googleServiceAccountEmail?: string;
  googlePrivateKey?: string;
}

export function buildEnvContent(answers: InitAnswers): string {
  const lines: string[] = [
    '# Cryyer Environment Variables',
    '# Generated by cryyer init',
    '',
    '# GitHub personal access token (repo scope required)',
    `GITHUB_TOKEN=${answers.githubToken}`,
    '',
    `# Email provider: ${EMAIL_PROVIDERS.join(', ')}`,
    `EMAIL_PROVIDER=${answers.emailProvider}`,
  ];

  if (answers.emailProvider === 'resend') {
    lines.push('', '# Resend API key for email delivery');
    lines.push(`RESEND_API_KEY=${answers.resendApiKey ?? ''}`);
  }

  lines.push(
    '',
    '# Default sender email address',
    `FROM_EMAIL=${answers.fromEmail}`,
    '',
    `# LLM provider: ${LLM_PROVIDERS.join(', ')}`,
    `LLM_PROVIDER=${answers.llmProvider}`,
    '',
    `# ${LLM_LABELS[answers.llmProvider]} API key`,
    `${LLM_KEY_NAMES[answers.llmProvider]}=${answers.llmApiKey}`,
    '',
    `# Subscriber store: ${SUBSCRIBER_STORES.join(', ')}`,
    `SUBSCRIBER_STORE=${answers.subscriberStore}`,
  );

  if (answers.subscriberStore === 'supabase') {
    lines.push('', '# Supabase configuration');
    lines.push(`SUPABASE_URL=${answers.supabaseUrl ?? ''}`);
    lines.push(`SUPABASE_SERVICE_KEY=${answers.supabaseServiceKey ?? ''}`);
  }

  if (answers.subscriberStore === 'google-sheets') {
    lines.push('', '# Google Sheets configuration');
    lines.push(`GOOGLE_SHEETS_SPREADSHEET_ID=${answers.googleSheetsSpreadsheetId ?? ''}`);
    lines.push(`GOOGLE_SERVICE_ACCOUNT_EMAIL=${answers.googleServiceAccountEmail ?? ''}`);
    lines.push(`GOOGLE_PRIVATE_KEY=${answers.googlePrivateKey ?? ''}`);
  }

  lines.push('');
  return lines.join('\n');
}

export function buildSubscribersJson(productId: string): string {
  const data = [
    { email: 'alice@example.com', name: 'Alice', productIds: [productId] },
  ];
  return JSON.stringify(data, null, 2) + '\n';
}

const EMAIL_SECRET_NAMES: Record<string, string> = {
  resend: 'RESEND_API_KEY',
  gmail: 'GMAIL_REFRESH_TOKEN',
};

const GITIGNORE_ENTRIES = ['.env', 'subscribers.json', 'email-log.json'];
const GITIGNORE_HEADER = '# cryyer';

export function buildGitignoreContent(existing: string | null): string {
  if (!existing) {
    return GITIGNORE_HEADER + '\n' + GITIGNORE_ENTRIES.join('\n') + '\n';
  }

  const existingLines = existing.split('\n');
  const missing = GITIGNORE_ENTRIES.filter(
    (entry) => !existingLines.some((line) => line.trim() === entry)
  );

  if (missing.length === 0) return existing;

  const suffix = existing.endsWith('\n') ? '' : '\n';
  return existing + suffix + '\n' + GITIGNORE_HEADER + '\n' + missing.join('\n') + '\n';
}

export function buildDraftWorkflowContent(productId: string, llmProvider: string): string {
  const secretName = LLM_KEY_NAMES[llmProvider] ?? 'ANTHROPIC_API_KEY';
  return `name: Draft Email

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  draft:
    if: startsWith(github.head_ref, 'release-please--')
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: read
    steps:
      - uses: actions/checkout@v4
        with:
          ref: \${{ github.head_ref }}
          fetch-depth: 0

      - name: Extract version from PR title
        id: version
        run: |
          VERSION=$(echo "\${{ github.event.pull_request.title }}" | grep -oP '\\d+\\.\\d+\\.\\d+' || echo "0.0.0")
          echo "value=$VERSION" >> "$GITHUB_OUTPUT"

      - name: Generate draft
        uses: atriumn/cryyer/.github/actions/draft-file@v0
        id: draft
        with:
          product: ${productId}
          version: \${{ steps.version.outputs.value }}
          llm-api-key: \${{ secrets.${secretName} }}
          llm-provider: ${llmProvider}

      - name: Commit draft
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add \${{ steps.draft.outputs.draft-path }}
          git diff --cached --quiet || git commit -m "chore: draft email for v\${{ steps.version.outputs.value }}"
          git push
`;
}

export function buildSendWorkflowContent(
  productId: string,
  emailProvider: string,
  subscriberStore: string,
): string {
  const emailInputs: string[] = [];
  if (emailProvider === 'resend') {
    emailInputs.push(`          email-api-key: \${{ secrets.RESEND_API_KEY }}`);
  } else if (emailProvider === 'gmail') {
    emailInputs.push(`          gmail-refresh-token: \${{ secrets.GMAIL_REFRESH_TOKEN }}`);
  }

  const storeInputs: string[] = [];
  if (subscriberStore === 'supabase') {
    storeInputs.push(`          supabase-url: \${{ secrets.SUPABASE_URL }}`);
    storeInputs.push(`          supabase-service-key: \${{ secrets.SUPABASE_SERVICE_KEY }}`);
  } else if (subscriberStore === 'google-sheets') {
    storeInputs.push(`          google-sheets-spreadsheet-id: \${{ secrets.GOOGLE_SHEETS_SPREADSHEET_ID }}`);
    storeInputs.push(`          google-service-account-email: \${{ secrets.GOOGLE_SERVICE_ACCOUNT_EMAIL }}`);
    storeInputs.push(`          google-private-key: \${{ secrets.GOOGLE_PRIVATE_KEY }}`);
  }

  const extraInputs = [...emailInputs, ...storeInputs].join('\n');
  const extraBlock = extraInputs ? '\n' + extraInputs : '';

  return `name: Send Email

on:
  release:
    types: [published]

jobs:
  send:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Extract version from tag
        id: version
        run: |
          VERSION=\${{ github.event.release.tag_name }}
          VERSION="\${VERSION#v}"
          echo "value=$VERSION" >> "$GITHUB_OUTPUT"

      - name: Send emails
        uses: atriumn/cryyer/.github/actions/send-file@v0
        with:
          product: ${productId}
          draft-path: drafts/v\${{ steps.version.outputs.value }}.md
          from-email: \${{ secrets.FROM_EMAIL }}
          email-provider: ${emailProvider}
          subscriber-store: ${subscriberStore}${extraBlock}
`;
}

function parseSelection(raw: string, options: readonly string[], defaultIndex: number): string {
  const trimmed = raw.trim();
  if (!trimmed) return options[defaultIndex];
  const num = parseInt(trimmed, 10);
  if (num >= 1 && num <= options.length) return options[num - 1];
  throw new Error(`Invalid selection: "${trimmed}". Enter a number 1-${options.length}.`);
}

export interface InitFlags {
  product?: string;
  repo?: string;
  voice?: string;
  llm?: string;
  subscriberStore?: string;
  emailProvider?: string;
  fromEmail?: string;
  yes?: boolean;
  workflows?: boolean;
}

export function parseInitFlags(argv: string[]): InitFlags {
  const flags: InitFlags = {};
  for (let i = 0; i < argv.length; i++) {
    const arg = argv[i];
    const next = argv[i + 1];
    switch (arg) {
      case '--product': flags.product = next; i++; break;
      case '--repo': flags.repo = next; i++; break;
      case '--voice': flags.voice = next; i++; break;
      case '--llm': flags.llm = next; i++; break;
      case '--subscriber-store': flags.subscriberStore = next; i++; break;
      case '--email-provider': flags.emailProvider = next; i++; break;
      case '--from-email': flags.fromEmail = next; i++; break;
      case '--yes': case '-y': flags.yes = true; break;
      case '--no-workflows': flags.workflows = false; break;
      case '--workflows': flags.workflows = true; break;
    }
  }
  return flags;
}

function isNonInteractive(flags: InitFlags): boolean {
  return !!(flags.yes || process.env.CI === 'true');
}

export async function main(): Promise<void> {
  const flags = parseInitFlags(process.argv.slice(2));
  const nonInteractive = isNonInteractive(flags);
  const rl = nonInteractive ? null : createInterface({ input, output });
  const cwd = process.cwd();

  async function ask(prompt: string, defaultValue?: string): Promise<string> {
    if (nonInteractive) return defaultValue ?? '';
    return rl!.question(prompt);
  }

  let version: string;
  try {
    version = getVersion();
  } catch {
    version = 'dev';
  }

  console.log('');
  console.log(`  cryyer v${version}`);
  console.log('');
  console.log(`  Setting up cryyer in ${cwd}`);
  console.log('');

  try {
    // Check if products already exist
    const productsDir = join(cwd, 'products');
    if (!nonInteractive && existsSync(productsDir)) {
      const existing = readdirSync(productsDir).filter((f) => f.endsWith('.yaml') || f.endsWith('.yml'));
      if (existing.length > 0) {
        console.log(`  Found existing products: ${existing.map((f) => f.replace(/\.ya?ml$/, '')).join(', ')}`);
        const rawAdd = await ask('  Add another product? (Y/n): ');
        if (rawAdd.trim().toLowerCase() === 'n') {
          console.log('  Skipping product setup.');
          console.log('');
          rl?.close();
          return;
        }
        console.log('');
      }
    }

    // --- Phase 1: Product ---
    const productName = flags.product || (await ask('? Product name: ')).trim();
    if (!productName) throw new Error('Product name is required');

    const repo = flags.repo || (await ask('? GitHub repo (owner/repo): ')).trim();
    if (!repo || !repo.includes('/')) throw new Error('GitHub repo must be in owner/repo format');

    const voice = flags.voice || (await ask('? Voice/tone: ')).trim();
    if (!voice) throw new Error('Voice/tone is required');

    const productId = sanitizeId(productName);
    const emailSubjectTemplate = `{{weekOf}} Weekly Update — ${productName}`;

    if (!nonInteractive) console.log('');

    // --- Phase 2: LLM provider ---
    let llmProvider: string;
    if (flags.llm) {
      if (!(LLM_PROVIDERS as readonly string[]).includes(flags.llm)) {
        throw new Error(`Invalid LLM provider: "${flags.llm}". Must be one of: ${LLM_PROVIDERS.join(', ')}`);
      }
      llmProvider = flags.llm;
    } else if (nonInteractive) {
      llmProvider = 'anthropic';
    } else {
      const llmPrompt = `? LLM provider (${LLM_PROVIDERS.map((p, i) => `${i + 1}=${LLM_LABELS[p]}`).join(', ')}) [1]: `;
      llmProvider = parseSelection(await ask(llmPrompt), LLM_PROVIDERS, 0);
    }

    // In non-interactive mode, read API key from env var
    const llmKeyEnv = LLM_KEY_NAMES[llmProvider];
    const llmApiKey = nonInteractive
      ? (process.env[llmKeyEnv] ?? '')
      : (await ask(`? ${LLM_KEY_PROMPTS[llmProvider]}: `)).trim();
    if (!llmApiKey && !nonInteractive) throw new Error(`${LLM_LABELS[llmProvider]} API key is required`);

    if (!nonInteractive) console.log('');

    // --- Phase 3: Subscriber store ---
    let subscriberStore: string;
    if (flags.subscriberStore) {
      if (!(SUBSCRIBER_STORES as readonly string[]).includes(flags.subscriberStore)) {
        throw new Error(`Invalid subscriber store: "${flags.subscriberStore}". Must be one of: ${SUBSCRIBER_STORES.join(', ')}`);
      }
      subscriberStore = flags.subscriberStore;
    } else if (nonInteractive) {
      subscriberStore = 'json';
    } else {
      const storePrompt = `? Subscriber store (${SUBSCRIBER_STORES.map((s, i) => `${i + 1}=${STORE_LABELS[s]}`).join(', ')}) [1]: `;
      subscriberStore = parseSelection(await ask(storePrompt), SUBSCRIBER_STORES, 0);
    }

    // Collect store-specific credentials
    let supabaseUrl: string | undefined;
    let supabaseServiceKey: string | undefined;
    let googleSheetsSpreadsheetId: string | undefined;
    let googleServiceAccountEmail: string | undefined;
    let googlePrivateKey: string | undefined;

    if (subscriberStore === 'supabase') {
      if (nonInteractive) {
        supabaseUrl = process.env.SUPABASE_URL;
        supabaseServiceKey = process.env.SUPABASE_SERVICE_KEY;
      } else {
        const rawUrl = await ask('? Supabase URL: ');
        supabaseUrl = rawUrl.trim();
        if (!supabaseUrl) throw new Error('Supabase URL is required');

        const rawKey = await ask('? Supabase service key: ');
        supabaseServiceKey = rawKey.trim();
        if (!supabaseServiceKey) throw new Error('Supabase service key is required');
      }
    }

    if (subscriberStore === 'google-sheets') {
      if (nonInteractive) {
        googleSheetsSpreadsheetId = process.env.GOOGLE_SHEETS_SPREADSHEET_ID;
        googleServiceAccountEmail = process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL;
        googlePrivateKey = process.env.GOOGLE_PRIVATE_KEY;
      } else {
        const rawId = await ask('? Google Sheets spreadsheet ID: ');
        googleSheetsSpreadsheetId = rawId.trim();
        if (!googleSheetsSpreadsheetId) throw new Error('Spreadsheet ID is required');

        const rawEmail = await ask('? Google service account email: ');
        googleServiceAccountEmail = rawEmail.trim();
        if (!googleServiceAccountEmail) throw new Error('Service account email is required');

        const rawPk = await ask('? Google private key: ');
        googlePrivateKey = rawPk.trim();
        if (!googlePrivateKey) throw new Error('Private key is required');
      }
    }

    if (!nonInteractive) console.log('');

    // --- Phase 4: Email provider ---
    let emailProvider: string;
    if (flags.emailProvider) {
      if (!(EMAIL_PROVIDERS as readonly string[]).includes(flags.emailProvider)) {
        throw new Error(`Invalid email provider: "${flags.emailProvider}". Must be one of: ${EMAIL_PROVIDERS.join(', ')}`);
      }
      emailProvider = flags.emailProvider;
    } else if (nonInteractive) {
      emailProvider = 'resend';
    } else {
      const emailPrompt = `? Email provider (${EMAIL_PROVIDERS.map((p, i) => `${i + 1}=${EMAIL_PROVIDER_LABELS[p]}`).join(', ')}) [1]: `;
      emailProvider = parseSelection(await ask(emailPrompt), EMAIL_PROVIDERS, 0);
    }

    if (!nonInteractive) console.log('');

    // --- Phase 5: Common credentials ---
    const githubToken = nonInteractive
      ? (process.env.GITHUB_TOKEN ?? '')
      : (await ask('? GitHub token (github.com/settings/tokens, "repo" scope): ')).trim();
    if (!githubToken && !nonInteractive) throw new Error('GitHub token is required');

    let resendApiKey: string | undefined;
    if (emailProvider === 'resend') {
      resendApiKey = nonInteractive
        ? (process.env.RESEND_API_KEY ?? '')
        : (await ask('? Resend API key (resend.com/api-keys): ')).trim();
      if (!resendApiKey && !nonInteractive) throw new Error('Resend API key is required');
    }

    const fromEmail = flags.fromEmail || (nonInteractive
      ? (process.env.FROM_EMAIL ?? '')
      : (await ask('? Sender email address: ')).trim());
    if (!fromEmail && !nonInteractive) throw new Error('Sender email address is required');

    if (!nonInteractive) console.log('');

    // --- Generate files ---
    const created: Array<[string, string]> = [];

    // 1. Product YAML
    if (!existsSync(productsDir)) {
      mkdirSync(productsDir, { recursive: true });
    }

    const yamlPath = join(productsDir, `${productId}.yaml`);
    let writeYaml = true;

    if (existsSync(yamlPath) && !nonInteractive) {
      const rawOverwrite = await ask(`  ${productId}.yaml already exists. Overwrite? (y/N): `);
      writeYaml = rawOverwrite.trim().toLowerCase() === 'y';
    }

    if (writeYaml) {
      const productConfig = { id: productId, name: productName, repo, emailSubjectTemplate, voice };
      const yaml = `# Product configuration for ${productName}\n` + stringifyYaml(productConfig);
      writeFileSync(yamlPath, yaml, 'utf-8');
      created.push([`products/${productId}.yaml`, 'Product configuration']);
    }

    // 2. .env (skip in non-interactive — secrets come from env vars already)
    const envPath = join(cwd, '.env');
    let writeEnv = !nonInteractive;

    if (writeEnv && existsSync(envPath)) {
      const rawOverwrite = await ask('  .env already exists. Overwrite? (y/N): ');
      writeEnv = rawOverwrite.trim().toLowerCase() === 'y';
    }

    if (writeEnv) {
      const answers: InitAnswers = {
        productName, repo, voice, llmProvider, llmApiKey,
        subscriberStore, emailProvider, githubToken, resendApiKey: resendApiKey ?? '', fromEmail,
        supabaseUrl, supabaseServiceKey,
        googleSheetsSpreadsheetId, googleServiceAccountEmail, googlePrivateKey,
      };
      const envContent = buildEnvContent(answers);
      writeFileSync(envPath, envContent, 'utf-8');
      created.push(['.env', 'API keys and settings']);
    }

    // 3. subscribers.json (only for JSON store)
    if (subscriberStore === 'json') {
      const subscribersPath = join(cwd, 'subscribers.json');
      if (!existsSync(subscribersPath)) {
        writeFileSync(subscribersPath, buildSubscribersJson(productId), 'utf-8');
        created.push(['subscribers.json', 'Subscriber list (edit to add emails)']);
      }
    }

    // 4. .gitignore
    const gitignorePath = join(cwd, '.gitignore');
    const existingGitignore = existsSync(gitignorePath)
      ? readFileSync(gitignorePath, 'utf-8')
      : null;
    const newGitignore = buildGitignoreContent(existingGitignore);

    if (newGitignore !== existingGitignore) {
      writeFileSync(gitignorePath, newGitignore, 'utf-8');
      created.push(['.gitignore', existingGitignore ? 'Updated with cryyer entries' : 'Ignores .env and data files']);
    }

    // --- Phase 6: GitHub Actions workflows ---
    let setupWorkflows: boolean;
    if (flags.workflows !== undefined) {
      setupWorkflows = flags.workflows;
    } else if (nonInteractive) {
      setupWorkflows = false;
    } else {
      const rawSetupWorkflows = await ask('? Set up GitHub Actions for release-triggered emails? (Y/n): ');
      setupWorkflows = rawSetupWorkflows.trim().toLowerCase() !== 'n';
    }
    const workflowSecrets: string[] = [];

    if (setupWorkflows) {
      const workflowsDir = join(cwd, '.github', 'workflows');
      mkdirSync(workflowsDir, { recursive: true });

      const draftWorkflowPath = join(workflowsDir, 'draft-email.yml');
      let writeDraftWorkflow = true;
      if (existsSync(draftWorkflowPath) && !nonInteractive) {
        const rawOverwrite = await ask('  draft-email.yml already exists. Overwrite? (y/N): ');
        writeDraftWorkflow = rawOverwrite.trim().toLowerCase() === 'y';
      }
      if (writeDraftWorkflow) {
        writeFileSync(draftWorkflowPath, buildDraftWorkflowContent(productId, llmProvider), 'utf-8');
        created.push(['.github/workflows/draft-email.yml', 'Draft email on release PR']);
      }

      const sendWorkflowPath = join(workflowsDir, 'send-email.yml');
      let writeSendWorkflow = true;
      if (existsSync(sendWorkflowPath) && !nonInteractive) {
        const rawOverwrite = await ask('  send-email.yml already exists. Overwrite? (y/N): ');
        writeSendWorkflow = rawOverwrite.trim().toLowerCase() === 'y';
      }
      if (writeSendWorkflow) {
        writeFileSync(sendWorkflowPath, buildSendWorkflowContent(productId, emailProvider, subscriberStore), 'utf-8');
        created.push(['.github/workflows/send-email.yml', 'Send email on release']);
      }

      workflowSecrets.push(LLM_KEY_NAMES[llmProvider]);
      workflowSecrets.push('FROM_EMAIL');
      if (emailProvider === 'resend') workflowSecrets.push('RESEND_API_KEY');
      if (emailProvider === 'gmail') workflowSecrets.push('GMAIL_REFRESH_TOKEN');
      if (subscriberStore === 'supabase') workflowSecrets.push('SUPABASE_URL', 'SUPABASE_SERVICE_KEY');
      if (subscriberStore === 'google-sheets') workflowSecrets.push('GOOGLE_SHEETS_SPREADSHEET_ID', 'GOOGLE_SERVICE_ACCOUNT_EMAIL', 'GOOGLE_PRIVATE_KEY');
    }

    console.log('');

    // --- Summary ---
    if (created.length > 0) {
      console.log('  Created:');
      const maxPath = Math.max(...created.map(([p]) => p.length));
      for (const [filePath, desc] of created) {
        console.log(`    ${filePath.padEnd(maxPath + 4)}${desc}`);
      }
    }

    console.log('');
    console.log('  Next steps:');
    let step = 1;
    if (workflowSecrets.length > 0) {
      console.log(`    ${step}. Set GitHub secrets  ${workflowSecrets.join(', ')}`);
      step++;
    }
    if (emailProvider === 'gmail') {
      console.log(`    ${step}. Authorize Gmail     npx @atriumn/cryyer auth gmail`);
      step++;
    }
    if (subscriberStore === 'json') {
      console.log(`    ${step}. Add subscribers     Edit subscribers.json`);
    } else if (subscriberStore === 'supabase') {
      console.log(`    ${step}. Add subscribers     Set up your Supabase beta_testers table`);
    } else {
      console.log(`    ${step}. Add subscribers     Add rows to your Google Sheet`);
    }
    step++;
    console.log(`    ${step}. Validate setup      npx @atriumn/cryyer check`);
    step++;
    console.log(`    ${step}. Preview a draft     npx @atriumn/cryyer run --dry-run`);
    console.log('');
    console.log('  Docs: https://cryyer.dev');
    console.log('');
  } finally {
    rl?.close();
  }
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  main().catch((err) => {
    console.error('Fatal error:', err);
    process.exit(1);
  });
}
